version: '3.8'
services: 
  server: 
    build: ./server
    container_name: server
    ports: 
      - '5000:5000'
    volumes: 
      - ./server:/app
      - /server/node_modules
  client:
    build: ./client
    container_name: client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /client/node_modules
    stdin_open: true
    tty: true
